name: Reusable Build & Push Docker

on:
  workflow_call:
    inputs:
      image-name: 
        description: Name of de Image
        required: false
        type: string
      context:
        description: Docker context (path) to start build from
        required: false
        type: string
      aws-region:
        description: AWS Region to use on registry
        required: false
        type: string
        default: eu-north-1
      role-to-assume:
        description: Role to assume
        required: false
        type: string
      push:
        description: Push image to registry
        required: false
        type: boolean
        default: true
      platforms:
        description: Platforms to build for
        required: false
        type: string
        default: linux/amd64 
      aws-ecr-repo:
        description: ECR Repository name
        required: false
        type: string
        default: dev-conquer-ecr-repo

permissions:
  id-token: write
  contents: read
  packages: write 
  pull-requests: write 

jobs:
  build-image:
    name: Build and Push
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}
      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - 
        name: Create new Repo Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -  
        name: Get Service to Build
        if: github.event_name == 'push'
        id: service-id
        run: |
          echo "service-name=$(git diff --name-only HEAD~1 | cut -d'/' -f1 | head -1 )" >> $GITHUB_OUTPUT
      - 
        name: Build and Push to AWS ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker buildx build --push --platform linux/amd64 \
          --tag ${{ env.REGISTRY }}/${{ inputs.app }}:${{ steps.tag_version.outputs.new_tag }} .
      - 
        name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.aws-ecr-repo }}
          ECR_CONTEXT: ${{ inputs.context }}
          IMAGE_TAG: ${{ inputs.image-name }}-${{ steps.tag_version.outputs.new_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ inputs.context }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
