on:
  push:
    branches:
      - main
    paths:
      - "worker/**"
 
  pull_request:
    paths: 
      - "worker/**"

jobs:

  call-docker-build:
    name: Call Docker Build
    uses: ./.github/workflows/reusable-docker-build.yaml

    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: write
    
    with:
      role-to-assume: ${{ vars.GH_IDP_AWS_ROLE_TO_ASSUME }}
      context: ./worker
      image-name: vottingapp-worker